services:
  ci:
    container_name: my-ci
    build: ./app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/scripts/Development/Gan-Shmuel:/Gan-Shmuel
    ports:
      - 8080:5000
    networks:
      - gan-shmuel

networks:
  gan-shmuel:
