services:
  ci:
    container_name: my-ci
    build: ./app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/logs:/logs
    environment:
      - SLACK_WEBHOOK_URL
    ports:
      - 8080:5000
    networks:
      - gan-shmuel

networks:
  gan-shmuel:
