version: "3"

services:
  db:
    build: ./db/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app/
    depends_on:
      - db
    environment:
      FLASK_ENV: production 
    ports: 
      - "4000:5000"
