version: "3"

services:
  db:
    build: ./db/
    container_name: billing-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: billdb
      MYSQL_USER: billing-user
      MYSQL_PASSWORD: secret
    networks:
      - billing-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app/
    container_name: billing-app
    depends_on:
      - db
    ports: 
      - "8081:5000"
    environment:
        DB_HOST: billing-db
    networks:
      - billing-network
    volumes:
      - ./app/app.py:/app/app.py
      - ./in:/in

volumes:
   mysql-data: 

networks:
  billing-network: