

services:
  web:
    depends_on:
      db:
          condition: service_healthy
    build: ./app/
    container_name: webapp_gs
    networks:
      - gsnetwork
    ports:
      - "5000:5000"



  db:
    build: ./db/
    container_name: db_gs
    networks:
      - gsnetwork
    ports:
      - "3306:3306"
    volumes:
      - gsdata:/var/lib/mysql
      - ./db/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  gsnetwork:

volumes:
  gsdata:
    external: true