

services:
  web_weight:
    depends_on:
      db_weight:
          condition: service_healthy
    build: ./app/
    container_name: webapp_gs
    environment:
      DB_HOST: db_gs
    networks:
      - prod_network 
    ports:
      - "8082:5000"
    # volumes:
    #   - ./app/in/:/app/in/



  db_weight:
    build: ./db/
    container_name: db_gs
    networks:
      - prod_network 
    volumes:
      - gsdata:/var/lib/mysql ##note -this is named volume!!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  prod_network:
    external: true

volumes:
  gsdata:

